#!/usr/bin/env bash

set -euo pipefail

repo_root="${GITHUB_WORKSPACE:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)}"
report_file="${SKILL_UPDATES_REPORT:-$repo_root/skill-updates-report.json}"
prs_file="${SKILL_UPDATES_PRS:-$repo_root/skill-updates-prs.json}"
base_branch="${SKILL_UPDATES_BASE_BRANCH:-distro/arch-omarchy}"
dot_command="${SKILL_UPDATES_DOT_COMMAND:-$repo_root/scripts/.local/bin/dot}"
dashboard_marker='<!-- skill-updates-dashboard -->'
pr_marker='<!-- automated-skill-update -->'

render_dashboard() {
  local report="$1"
  local prs="$2"
  local generated_at
  generated_at="$(date -u +'%Y-%m-%d %H:%M UTC')"

  printf '%s\n\n' "$dashboard_marker"
  printf 'Imported skills that need attention. Clean updates open one pull request per skill.\n\n'
  printf 'Last checked: %s\n\n' "$generated_at"

  printf '## Manual review\n\n'
  if [[ "$(jq '[.skills[] | select(.state == "manual-review")] | length' "$report")" -eq 0 ]]; then
    printf 'None.\n'
  else
    jq -r '.skills[] | select(.state == "manual-review") | "- **\(.name)**: `\(.storedSha // "unknown")` -> `\(.upstreamSha // "unknown")`\n  - \(.origin)\n  - Local edits: \(.localEdits | join("; "))"' "$report"
  fi

  printf '\n## Open update PRs\n\n'
  if [[ ! -s "$prs" ]] || [[ "$(jq 'length' "$prs")" -eq 0 ]]; then
    printf 'None.\n'
  else
    jq -r '.[] | "- [#\(.number) \(.title)](\(.url))"' "$prs"
  fi

  printf '\n## Problems\n\n'
  if [[ "$(jq '[.skills[] | select(.state == "invalid-origin" or .state == "origin-gone" or .state == "error")] | length' "$report")" -eq 0 ]]; then
    printf 'None.\n'
  else
    jq -r '.skills[] | select(.state == "invalid-origin" or .state == "origin-gone" or .state == "error") | "- **\(.name)** (`\(.state)`): \(.reason // "Unknown error")"' "$report"
  fi
}

if [[ "${1:-}" == "render-dashboard" ]]; then
  render_dashboard "$report_file" "$prs_file"
  exit 0
fi

cd "$repo_root"

git config user.name 'skill-updates[bot]'
git config user.email 'skill-updates[bot]@users.noreply.github.com'

"$dot_command" skill-updates --json >"$report_file"

gh label create skill-update --color 0e8a16 --description 'Automated imported skill update' --force
gh label create skill-updates-dashboard --color 1d76db --description 'Imported skill update status' --force

mapfile -t clean_updates < <(
  jq -r '.skills[] | select(.state == "update-available") | .name' "$report_file"
)

for skill in "${clean_updates[@]}"; do
  item="$(jq -c --arg skill "$skill" '.skills[] | select(.name == $skill)' "$report_file")"
  skill_dir="$(jq -r '.directory' <<<"$item")"
  skill_path="agents/.agents/skills/$skill_dir"
  branch="skill-update/$skill_dir"
  old_sha="$(jq -r '.storedSha // "unknown"' <<<"$item")"
  new_sha="$(jq -r '.upstreamSha // "unknown"' <<<"$item")"
  origin="$(jq -r '.origin' <<<"$item")"
  files="$(jq -r '.files[] | "- `\(.path)` (\(.status))"' <<<"$item")"

  git checkout -B "$branch" "origin/$base_branch"
  "$dot_command" skill-updates --update --skill "$skill" --no-commit

  if [[ -z "$(git status --porcelain -- "$skill_path")" ]]; then
    printf 'No generated changes for %s; skipping PR.\n' "$skill"
    continue
  fi

  git add -- "$skill_path"
  git commit -m "Update skill: $skill"
  git push --force-with-lease origin "$branch"

  body_file="$(mktemp)"
  cat >"$body_file" <<EOF
${pr_marker}

Update the imported \`$skill\` skill from its tracked upstream origin.

- Origin: $origin
- SHA: \`$old_sha\` -> \`$new_sha\`

## Files

$files

Generated by the Skill updates workflow.
EOF

  if pr_url="$(gh pr list --head "$branch" --state open --json url --jq '.[0].url')" && [[ -n "$pr_url" ]]; then
    gh pr edit "$pr_url" --title "Update skill: $skill" --body-file "$body_file" --add-label skill-update
  else
    gh pr create --base "$base_branch" --head "$branch" --title "Update skill: $skill" --body-file "$body_file" --label skill-update
  fi
  rm -f "$body_file"
done

git checkout --detach "origin/$base_branch"

mapfile -t open_skill_prs < <(gh pr list --state open --label skill-update --limit 1000 --json number,title,url,headRefName,body --jq '.[] | @base64')

for encoded in "${open_skill_prs[@]}"; do
  pr="$(base64 --decode <<<"$encoded")"
  branch="$(jq -r '.headRefName' <<<"$pr")"
  body="$(jq -r '.body' <<<"$pr")"
  if [[ "$branch" != skill-update/* ]] || [[ "$body" != *"$pr_marker"* ]]; then
    continue
  fi
  skill="${branch#skill-update/}"
  if ! jq -e --arg skill "$skill" '.skills[] | select(.state == "update-available" and .directory == $skill)' "$report_file" >/dev/null; then
    number="$(jq -r '.number' <<<"$pr")"
    gh pr close "$number" --delete-branch --comment 'Upstream no longer differs from the tracked skill.'
  fi
done

gh pr list --state open --label skill-update --limit 1000 --json number,title,url >"$prs_file"
dashboard_file="$(mktemp)"
render_dashboard "$report_file" "$prs_file" >"$dashboard_file"

dashboard_number="$(gh issue list --state open --label skill-updates-dashboard --limit 10 --json number,body --jq "map(select(.body | contains(\"$dashboard_marker\")))[0].number // empty")"
if [[ -n "$dashboard_number" ]]; then
  gh issue edit "$dashboard_number" --title 'Skill updates' --body-file "$dashboard_file" --add-label skill-updates-dashboard
else
  gh issue create --title 'Skill updates' --body-file "$dashboard_file" --label skill-updates-dashboard
fi

rm -f "$dashboard_file"
