#!/usr/bin/env zsh
if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.config/dotfiles
fi

if [[ ! -d $DOTFILES ]]; then
    echo "Dotfiles directory not found: $DOTFILES"
    exit 1
fi

if [[ -z $STOW_FOLDERS ]]; then
    # Get list of folders in the dotfiles directory
    pushd "$DOTFILES" >/dev/null || exit 1
    STOW_FOLDERS=$(printf '%s,' */)
    STOW_FOLDERS=${STOW_FOLDERS//\//}
    STOW_FOLDERS=${STOW_FOLDERS%,}
    popd >/dev/null || exit 1
fi

# -----------------------------
# Backup existing dotfiles
# -----------------------------
echo "Backup existing dotfiles"
if [[ -f $HOME/.zshrc ]]; then
    mkdir -p "$DOTFILES/backup"
    mv "$HOME/.zshrc" "$DOTFILES/backup"
fi

if [[ -f $HOME/.editorconfig ]]; then
    mkdir -p "$DOTFILES/backup"
    mv "$HOME/.editorconfig" "$DOTFILES/backup"
fi

if [[ -f $HOME/.config/ghostty/config.toml ]]; then
    mkdir -p "$DOTFILES/backup/.config/ghostty"
    mv "$HOME/.config/ghostty/config.toml" "$DOTFILES/backup/.config/ghostty"
fi

if [[ -d $HOME/.config/nvim ]]; then
    mkdir -p "$DOTFILES/backup/.config"
    mv "$HOME/.config/nvim" "$DOTFILES/backup/.config"
fi

pushd "$DOTFILES" >/dev/null || exit 1
for folder in ${(s:,:)STOW_FOLDERS}
do
    # Ignore backup folder
    if [[ $folder == "backup" ]]; then
        continue
    fi

    echo "stow $folder"
    stow -D "$folder"
    if [[ $folder == "opencode" ]]; then
        stow --no-folding --adopt "$folder"
    else
        stow --adopt "$folder"
    fi
done
popd >/dev/null || exit 1
