#!/usr/bin/env zsh

function log_amber() {
  echo -e "\e[38;5;214m$1\e[0m"
}

function log_green() {
  echo -e "\e[38;5;46m$1\e[0m"
}

function log_section() {
  echo
  log_green "------------------------------------------"
  log_green "$1"
  log_green "------------------------------------------"
}

# Update repositories
yay -Syu

# Define default yay flags and allow overriding via script args
DEFAULT_YAY_FLAGS=(--noconfirm --needed)
YAY_FLAGS=("${DEFAULT_YAY_FLAGS[@]}")
# Process script arguments
for arg in "$@"; do
  case "$arg" in
  --confirm)
    # Remove --noconfirm to require user confirmation
    YAY_FLAGS=("${YAY_FLAGS[@]/--noconfirm/}")
    ;;
  *)
    echo "Unknown option: $arg"
    exit 1
    ;;
  esac
done
# Prepare the install command as an array to preserve flags
install_command=(yay -S "${YAY_FLAGS[@]}")

log_section "Root (dotfiles management & tooling)"
${install_command[@]} \
  base-devel git stow yay-bin zsh

log_section "gamescope/"
${install_command[@]} \
  gamescope

log_section "ghostty/"
${install_command[@]} \
  ghostty

log_section "hyprland/"
${install_command[@]} \
  blueman flatpak hyprland network-manager-applet polkit-gnome swaybg wl-clipboard

log_section "hyprland/.config/hypr/scripts/"
${install_command[@]} \
  edid-decode jq vkbasalt

log_section "lazygit/"
${install_command[@]} \
  lazygit

log_section "nvim/"
${install_command[@]} \
  go neovim nodejs python python-pip ripgrep uv
npm install -g prettier

log_section "qt5ct/"
${install_command[@]} \
  qt5ct

log_section "starship/"
${install_command[@]} \
  starship

log_section "swaync/"
${install_command[@]} \
  swaync

log_section "waybar/"
${install_command[@]} \
  playerctl python-gobject waybar

log_section "wofi/"
${install_command[@]} \
  wofi

# Add a note
echo
echo
log_amber "This is not every package needed for"
log_amber "these dotfiles, but it's a good"
log_amber "starting point."
echo
echo
