#!/usr/bin/env zsh
if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.config/dotfiles
fi

if [[ ! -d $DOTFILES ]]; then
    echo "Dotfiles directory not found: $DOTFILES"
    exit 1
fi

if [[ -z $STOW_FOLDERS ]]; then
    # Get list of folders in the dotfiles directory
    pushd "$DOTFILES" >/dev/null || exit 1
    STOW_FOLDERS=$(printf '%s,' */)
    STOW_FOLDERS=${STOW_FOLDERS//\//}
    STOW_FOLDERS=${STOW_FOLDERS%,}
    popd >/dev/null || exit 1
fi

pushd "$DOTFILES" >/dev/null || exit 1
for folder in ${(s:,:)STOW_FOLDERS}
do
    # Ignore backup folder
    if [[ $folder == "backup" ]]; then
        continue
    fi

    echo "stow $folder"
    stow "$folder"
done
popd >/dev/null || exit 1
