import { Effect } from "effect";
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { Config } from "../services/Config.js";
import { OutputLog } from "../services/OutputLog.js";

type CompletionShell = "zsh";

const ZSH_COMPLETION_RELATIVE_PATH = "zsh/.local/share/zsh/site-functions/_dot";

const zshCompletion = String.raw`#compdef dot
# Generated by dot completions zsh. Do not edit by hand.

local -a dot_commands
dot_commands=(
  'init:Run one-time first-use machine setup'
  'install:Ensure prerequisites, then backup/adopt dotfiles'
  'update:Pull repos, stow dotfiles, install deps, rebuild'
  'stow:Re-stow public/private dotfiles'
  'doctor:Run dotfiles system health checks'
  'clean:Unstow managed dotfiles'
  'git-diff:Open the git diff/repo watcher view'
  'diff:Alias for git-diff'
  'git-log:Open recent commits across tracked repos'
  'git-workflows:Open watched GitHub workflow runs'
  'git-notifications:Open GitHub notification inbox'
  'notes:Open repository notes or run note utilities'
  'handoffs:Open handoff notes'
  'handoff:Alias for handoffs'
  'note:Read, write, or delete note files'
  'agents-sync:Sync AGENTS.md to Cursor rule'
  'opencode-debug:Debug OpenCode config and paths'
  'setup-private-repo:Register private pacman repo include'
  'private-pkg-publish:Build and publish a private package'
  'skill-updates:Check/apply imported skill updates'
  'skill-check:Validate skill references'
  'completions:Generate shell completions'
  'omarchy:Open an Omarchy submenu by path'
  'help:Show help'
)

local -a dot_init_hosts dot_notes_commands dot_note_commands dot_note_formats
dot_init_hosts=('desktop:Desktop Hypr host' 'laptop:Laptop Hypr host')
dot_notes_commands=(
  'root:Print the notes vault root'
  'context:Print OpenCode notes context'
  'list:List repository notes'
)
dot_note_commands=(
  'read:Print a note file'
  'write:Write stdin to a note file and commit it'
  'delete:Delete a note file and commit it'
)
dot_note_formats=('labels:Human-readable note labels' 'json:JSON output')

local -a dot_omarchy_submenus
dot_omarchy_submenus=(
  'theme:Theme management'
  'font:Font management'
  'toggle:Toggle system features'
  'capture:Screenshots and recordings'
  'system:Lock, logout, reboot, shutdown'
  'launch:Launch applications'
  'refresh:Refresh system components'
  'restart:Restart system services'
  'install:Install software and tools'
  'remove:Remove software and features'
  'packages:Package management'
  'share:Share clipboard, files, folders'
  'reminder:Reminders'
  'setup:DNS, security setup'
  'snapshot:System snapshots'
  'brightness:Display and keyboard brightness'
  'power:Power profiles'
)

_dot_path_option() {
  _arguments -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '--path[Note file path]:file:_files' \
    '*::arg:->args'
}

_dot_git_diff() {
  _arguments -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '--no-fetch[Skip fetching from remotes]' \
    '--raw[Text summary of repos with changes]' \
    '--bar-json[JSON output for status bars and shell modules]' \
    '--list-changed[Changed repos as rows]' \
    '--list-all[All tracked repos as rows]' \
    '--tab[Initial TUI pane]:tab:(changed other unchanged)' \
    '*::arg:->args'
}

_dot_git_workflows() {
  _arguments -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '--raw[Text summary of watched workflow runs]' \
    '--bar-json[JSON output for status bars and shell modules]' \
    '--list-repos[Watched repo summaries as rows]' \
    '--list-runs[Workflow runs as rows]' \
    '--since[Only include runs active at or after date]:date:' \
    '*::arg:->args'
}

_dot_git_notifications() {
  _arguments -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '--raw[Text summary of notification threads]' \
    '--bar-json[JSON output for status bars and shell modules]' \
    '--list-threads[Notification threads as rows]' \
    '--bar-filter[Apply watched-repo filtering]' \
    '--all[Include read notifications]' \
    '--participating[Only include participating or mentioned threads]' \
    '--since[Only include notifications updated after date]:date:' \
    '--mark-read[Mark a notification thread as read]:thread id:' \
    '--mark-bot-read[Mark unread bot notifications as read]' \
    '--dry-run[Preview --mark-bot-read without mutating GitHub state]' \
    '--mark-done[Mark a notification thread as done]:thread id:' \
    '--ignore[Ignore future notifications for a thread]:thread id:' \
    '--unignore[Stop ignoring future notifications for a thread]:thread id:' \
    '*::arg:->args'
}

_dot_notes() {
  local state
  _arguments -C -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '--all[Show notes from every repo-notes directory]' \
    '1:notes command:->notes_command' \
    '*::arg:->notes_args' && return

  case $state in
    notes_command)
      _describe -t commands 'notes command' dot_notes_commands
      ;;
    notes_args)
      case \${words[2]} in
        root)
          _arguments -S '--repo-notes[Print repository notes directory]'
          ;;
        context)
          _arguments -S '--command[OpenCode command name]:command:'
          ;;
        list)
          _arguments -S \
            '--all[List notes from every repo-notes directory]' \
            '--format[Output format]:format:((labels\:Human-readable\ note\ labels json\:JSON\ output))'
          ;;
      esac
      ;;
  esac
}

_dot_note() {
  local state
  _arguments -C -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '1:note command:->note_command' \
    '*::arg:->note_args' && return

  case $state in
    note_command)
      _describe -t commands 'note command' dot_note_commands
      ;;
    note_args)
      case \${words[2]} in
        read|delete)
          _dot_path_option
          ;;
        write)
          _arguments -S \
            '(-h --help)'{-h,--help}'[Show help message]' \
            '--path[Note file path]:file:_files' \
            '--stdin[Read note content from stdin]' \
            '*::arg:->args'
          ;;
      esac
      ;;
  esac
}

_dot_omarchy() {
  _arguments -S \
    '(-h --help)'{-h,--help}'[Show help message]' \
    '*:submenu:_describe -t submenus "omarchy submenu" dot_omarchy_submenus'
}

_dot_complete_command() {
  local command=$1

  case $command in
    init)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--confirm[Acknowledge non-interactive package helpers]' \
        '--noninteractive[Skip interactive prompts]' \
        '--interactive[Allow interactive prompts]' \
        '--host[Hypr host to link before stow]:host:_describe -t hosts "host" dot_init_hosts' \
        '--log[Init log path]:file:_files' \
        '--branch[Branch override for non-bootstrap Omarchy repos]:branch:' \
        '--bootstrap-branch[Branch override for bootstrap]:branch:' \
        '*::arg:->args'
      ;;
    update)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--pull[Pull repos only]' \
        '--stow[Stow only]' \
        '--tui[Install deps and rebuild dot binary only]' \
        '*::arg:->args'
      ;;
    stow)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--public[Stow public dotfiles only]' \
        '--private[Stow private dotfiles only]' \
        '*::arg:->args'
      ;;
    doctor|skill-check)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--open-opencode[Run checks then open OpenCode analysis]' \
        '*::arg:->args'
      ;;
    git-diff|diff)
      _dot_git_diff
      ;;
    git-log)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--raw[Text summary of recent commits]' \
        '*::arg:->args'
      ;;
    git-workflows)
      _dot_git_workflows
      ;;
    git-notifications)
      _dot_git_notifications
      ;;
    notes)
      _dot_notes
      ;;
    handoffs|handoff)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--all[Show handoff notes from every repo-notes directory]' \
        '*::arg:->args'
      ;;
    note)
      _dot_note
      ;;
    opencode-debug)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--agent[Debug a specific OpenCode agent]:agent:' \
        '*::arg:->args'
      ;;
    private-pkg-publish)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--no-git[Skip package repo commit and push]' \
        '--skip-build[Publish an existing dist package artifact]' \
        '--install[Install the published package after syncing mirror]' \
        '1:package name:' \
        '*::arg:->args'
      ;;
    skill-updates)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--check[Check only without applying]' \
        '--update[Auto-apply clean updates]' \
        '--skip-review[Skip local-edit review]' \
        '*::arg:->args'
      ;;
    completions)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '--stdout[Print completion script instead of writing it]' \
        '1:shell:(zsh)' \
        '*::arg:->args'
      ;;
    omarchy)
      _dot_omarchy
      ;;
    install|clean|agents-sync|setup-private-repo|help)
      _arguments -S \
        '(-h --help)'{-h,--help}'[Show help message]' \
        '*::arg:->args'
      ;;
  esac
}

if (( CURRENT > 2 )); then
  local command=\${words[2]}
  shift words
  (( CURRENT-- ))
  _dot_complete_command "$command"
  return
fi

local state
_arguments -C -S \
  '(-h --help)'{-h,--help}'[Show help message]' \
  '1:dot command:->command' && return

case $state in
  command)
    _describe -t commands 'dot command' dot_commands
    ;;
esac
`;

interface CompletionOptions {
  readonly shell?: CompletionShell;
  readonly stdout?: boolean;
}

function parseCompletionArgs(args: readonly string[]): CompletionOptions {
  if (args.includes("--help") || args.includes("-h")) {
    return { stdout: true };
  }

  const shellArg = args.find((arg) => !arg.startsWith("-"));
  const shell = shellArg ?? "zsh";
  if (shell !== "zsh") {
    console.error(`dot completions: unsupported shell '${shell}'`);
    process.exit(1);
  }

  return { shell, stdout: args.includes("--stdout") };
}

function printCompletionsHelp(): void {
  console.log(`Usage: dot completions [zsh] [--stdout]

Generate shell completions for dot.

By default this writes the managed Zsh completion file in the public dotfiles
repo so the next dot stow installs it to ~/.local/share/zsh/site-functions/_dot.

Options:
  --stdout    Print the completion script instead of writing it
  --help, -h  Show this help message

Examples:
  dot completions zsh
  dot completions zsh --stdout`);
}

/** Render the Zsh completion script for `dot`. */
export function renderZshCompletions(): string {
  return `${zshCompletion}\n`;
}

/** Write generated Zsh completions into the public dotfiles stow package. */
export const writeZshCompletions = Effect.gen(function* () {
  const config = yield* Config;
  const target = join(config.publicDotfiles, ZSH_COMPLETION_RELATIVE_PATH);
  yield* Effect.sync(() => {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, renderZshCompletions());
  });
  return target;
});

/** Generate shell completions for `dot`. */
export function completions(args: readonly string[] = []) {
  return Effect.gen(function* () {
    if (args.includes("--help") || args.includes("-h")) {
      yield* Effect.sync(printCompletionsHelp);
      return;
    }

    const options = parseCompletionArgs(args);
    if (options.stdout) {
      yield* Effect.sync(() => process.stdout.write(renderZshCompletions()));
      return;
    }

    const target = yield* writeZshCompletions;
    const log = yield* OutputLog;
    yield* log.info(
      `Generated ${options.shell ?? "zsh"} completions: ${target}`,
    );
  });
}
