customCommands:
  - key: <c-b>
    context: localBranches
    command: gh poi
    description: Clean up merged branches
    output: terminal
  - key: <c-f>
    context: localBranches
    command: git-rebase-default
    description: Fetch and rebase onto remote default branch
    output: terminal
