import { join } from "path";
import { writeFileAtomic } from "./atomicWrite.js";
import type { GitRepoShortcut } from "../services/GitConfig.js";
import type { CaptureRepositoryOption } from "../commands/NotesCaptureSync.js";

function quoteZsh(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/** Render Herdr-aware Zsh repository shortcuts from managed repositories. */
export function renderRepoShortcuts(
  repositories: readonly GitRepoShortcut[],
): string {
  const functions = repositories.flatMap((repo) =>
    repo.aliases.map(
      (alias) =>
        `function ${alias}() {\n  _repo_open ${quoteZsh(repo.name)} ${quoteZsh(repo.path)}\n}`,
    ),
  );

  return [
    "# Generated by dot from dot-git.yml. Do not edit.",
    "",
    ...functions.flatMap((fn) => [fn, ""]),
  ].join("\n");
}

/** Write the generated Zsh repository shortcuts into dot's cache directory. */
export function writeRepoShortcuts(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-shortcuts.zsh");

  writeFileAtomic(target, renderRepoShortcuts(repositories), {
    createDirectory: true,
  });

  return target;
}

/** Write managed repositories for the Herdr repository picker. */
export function writeRepoPicker(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-picker.json");

  writeFileAtomic(
    target,
    `${JSON.stringify(
      repositories.map(({ name, path, herdrAfter }) => ({
        name,
        path,
        ...(herdrAfter && { herdrAfter }),
      })),
      null,
      2,
    )}\n`,
    { createDirectory: true },
  );

  return target;
}

/** Write repository options consumed by the local Notes capture panel. */
export function writeCaptureRepositoryOptions(
  cacheDir: string,
  repositories: readonly CaptureRepositoryOption[],
): string {
  const target = join(cacheDir, "notes-capture-repositories.json");

  writeFileAtomic(target, `${JSON.stringify(repositories, null, 2)}\n`, {
    createDirectory: true,
  });

  return target;
}
