import { mkdirSync, renameSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import type { GitRepoShortcut } from "../services/GitConfig.js";

function quoteZsh(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/** Render Herdr-aware Zsh repository shortcuts from managed repositories. */
export function renderRepoShortcuts(
  repositories: readonly GitRepoShortcut[],
): string {
  const functions = repositories.flatMap((repo) =>
    repo.aliases.map(
      (alias) =>
        `function ${alias}() {\n  _repo_open ${quoteZsh(repo.name)} ${quoteZsh(repo.path)}\n}`,
    ),
  );

  return [
    "# Generated by dot from dot-git.yml. Do not edit.",
    "",
    ...functions.flatMap((fn) => [fn, ""]),
  ].join("\n");
}

/** Write the generated Zsh repository shortcuts into dot's cache directory. */
export function writeRepoShortcuts(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-shortcuts.zsh");
  const temporary = `${target}.tmp`;
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(temporary, renderRepoShortcuts(repositories));
  renameSync(temporary, target);
  return target;
}

/** Write managed repositories for the Herdr repository picker. */
export function writeRepoPicker(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-picker.json");
  const temporary = `${target}.tmp`;
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(
    temporary,
    `${JSON.stringify(
      repositories.map(({ name, path }) => ({ name, path })),
      null,
      2,
    )}\n`,
  );
  renameSync(temporary, target);
  return target;
}
