import { join } from "path";
import { writeFileAtomic } from "./atomicWrite.js";
import type { GitRepoShortcut } from "../services/GitConfig.js";
import type { CaptureRepositoryOption } from "../commands/NotesCaptureSync.js";

function quoteZsh(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/** Render Herdr-aware Zsh repository shortcuts from managed repositories. */
export function renderRepoShortcuts(
  repositories: readonly GitRepoShortcut[],
): string {
  const functions = repositories.flatMap((repo) =>
    repo.aliases.map(
      (alias) =>
        `function ${alias}() {\n  _repo_open ${quoteZsh(repo.name)} ${quoteZsh(repo.path)}\n}`,
    ),
  );

  return [
    "# Generated by dot from dot-git.yml. Do not edit.",
    "",
    ...functions.flatMap((fn) => [fn, ""]),
  ].join("\n");
}

/** Write the generated Zsh repository shortcuts into dot's cache directory. */
export function writeRepoShortcuts(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-shortcuts.zsh");

  writeFileAtomic(target, renderRepoShortcuts(repositories), {
    createDirectory: true,
  });

  return target;
}

/**
 * Order picker entries like Herdr workspaces: each entry follows its
 * `herdr_after` predecessor, and chains sharing a `[Tag]` prefix stay together
 * at the position of the first one. Unresolvable entries keep config order.
 */
function orderRepoPicker(
  repositories: readonly GitRepoShortcut[],
): readonly GitRepoShortcut[] {
  const names = new Set(repositories.map((repo) => repo.name));
  const visited = new Set<GitRepoShortcut>();

  const chain = (root: GitRepoShortcut): GitRepoShortcut[] => {
    if (visited.has(root)) return [];
    visited.add(root);

    return [
      root,
      ...repositories
        .filter((repo) => repo.herdrAfter === root.name)
        .flatMap(chain),
    ];
  };

  const chains = repositories.flatMap((repo) =>
    repo.herdrAfter === undefined ||
    repo.herdrAfter === repo.name ||
    !names.has(repo.herdrAfter)
      ? [chain(repo)]
      : [],
  );

  const leftovers = repositories.filter((repo) => !visited.has(repo));

  const groups = new Map<string, GitRepoShortcut[][]>();

  for (const [index, entries] of chains.entries()) {
    const tag = /^\[[^\]]+\]/.exec(entries[0]?.name ?? "")?.[0] ?? `#${index}`;
    groups.set(tag, [...(groups.get(tag) ?? []), entries]);
  }

  return [...[...groups.values()].flat(2), ...leftovers];
}

/** Write managed repositories for the Herdr repository picker. */
export function writeRepoPicker(
  cacheDir: string,
  repositories: readonly GitRepoShortcut[],
): string {
  const target = join(cacheDir, "repo-picker.json");

  writeFileAtomic(
    target,
    `${JSON.stringify(
      orderRepoPicker(repositories).map(({ name, path, herdrAfter }) => ({
        name,
        path,
        ...(herdrAfter && { herdrAfter }),
      })),
      null,
      2,
    )}\n`,
    { createDirectory: true },
  );

  return target;
}

/** Write repository options consumed by the local Notes capture panel. */
export function writeCaptureRepositoryOptions(
  cacheDir: string,
  repositories: readonly CaptureRepositoryOption[],
): string {
  const target = join(cacheDir, "notes-capture-repositories.json");

  writeFileAtomic(target, `${JSON.stringify(repositories, null, 2)}\n`, {
    createDirectory: true,
  });

  return target;
}
