# Laptop look overrides.
general {
    gaps_in = 0
    col.active_border = rgba(cccccc66)
    col.inactive_border = rgba(59595966)
}

decoration {
    rounding = 1
}

# Smaller floating terminal for SUPER+SHIFT+Q launcher
windowrule = size 760 500, match:class ^org\.omarchy\.terminal$
