# Desktop host marker.
env = OMARCHY_HOST,desktop

# Nvidia + Wayland (desktop has an Nvidia GPU).
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __NV_PRIME_RENDER_OFFLOAD,1
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
