-- Generated by float-app. Do not edit by hand.
hl.window_rule({ match = { class = "^chrome-capture\\.notes\\.timmo\\.dev__-Default$" }, tag = "+floating-window" })
hl.window_rule({ match = { class = "^chrome-beta\\.floatplane\\.com__post_CRPhG7Qjyb-Default$" }, tag = "+floating-window" })
hl.window_rule({ match = { class = "^music-assistant-companion$" }, tag = "+floating-window" })
hl.window_rule({ match = { class = "^org\\.kde\\.kdeconnect\\.app$" }, tag = "+floating-window" })
hl.window_rule({ match = { class = "^com\\.vysp3r\\.ProtonPlus$" }, tag = "+floating-window" })
