###-begin-dot-completions-###
#
# Static completion script for Fish
#
# Installation:
#   dot --completions fish > ~/.config/fish/completions/dot.fish
#

complete -c dot -n '__fish_use_subcommand' -f
complete -c dot -n '__fish_use_subcommand' -f -a 'init' -d 'Run one-time first-use machine setup'
complete -c dot -n '__fish_use_subcommand' -f -a 'install' -d 'Ensure prerequisites, then backup/adopt dotfiles'
complete -c dot -n '__fish_use_subcommand' -f -a 'update' -d 'Self-update, pull repos, stow dotfiles, rebuild. Phase flags are inclusive: passing any of --pull, --stow, or --app runs only the selected phases. Internal --no-self-update and --post-hook-repo flags support the active self-update handoff.'
complete -c dot -n '__fish_use_subcommand' -f -a 'up' -d 'Alias for update'
complete -c dot -n '__fish_use_subcommand' -f -a 'system-update' -d 'Select and run Dotfiles, Omarchy, and Topgrade updates'
complete -c dot -n '__fish_use_subcommand' -f -a 'stow' -d 'Re-stow public/private dotfiles'
complete -c dot -n '__fish_use_subcommand' -f -a 'omarchy-plugin' -d 'Manage Omarchy plugin submodules. The manage-omarchy-plugin compatibility wrapper may pass trailing 0/1 confirmation and commit-offer values to update and remove.'
complete -c dot -n '__fish_use_subcommand' -f -a 'omarchy-shell-config' -d 'Regenerate the Omarchy shell layout'
complete -c dot -n '__fish_use_subcommand' -f -a 'firewall' -d 'Reconcile managed ufw firewall rules'
complete -c dot -n '__fish_use_subcommand' -f -a 'doctor' -d 'Run parallel health checks for dependencies, repositories, stow integrity, services, packages, browser configuration, hardware video, firewall rules, and OpenCode/Herdr integration. A timestamped report is always written under ~/.local/state/dot/logs/.'
complete -c dot -n '__fish_use_subcommand' -f -a 'clean' -d 'Unstow managed dotfiles'
complete -c dot -n '__fish_use_subcommand' -f -a 'agents-sync' -d 'Mirror AGENTS.md to agent harness instruction files'
complete -c dot -n '__fish_use_subcommand' -f -a 'notes-capture-sync' -d 'Sync watched repositories to the notes capture picker'
complete -c dot -n '__fish_use_subcommand' -f -a 'setup-private-repo' -d 'Sync and register the private pacman repository'
complete -c dot -n '__fish_use_subcommand' -f -a 'setup-public-repo' -d 'Trust and register the public timmo pacman repository'
complete -c dot -n '__fish_use_subcommand' -f -a 'git-diff' -d 'Show repository change state across all tracked repositories.'
complete -c dot -n '__fish_use_subcommand' -f -a 'diff' -d 'Alias for git-diff'
complete -c dot -n '__fish_use_subcommand' -f -a 'git-commit' -d 'Commit staged changes through the guarded gateway. Subjects must be one line, have no trailing full stop, and stay within the hard length limit. Explicit --path scopes never imply git add -A; --amend keeps the existing message unless --message is supplied.'
complete -c dot -n '__fish_use_subcommand' -f -a 'git-notifications' -d 'Open the authenticated GitHub notification inbox. Without machine-output or action flags, this opens the Omarchy shell panel. --since accepts ISO/RFC dates, epoch timestamps, compact durations such as 2d, and quoted durations such as "2 days ago".'
complete -c dot -n '__fish_use_subcommand' -f -a 'mcp-sync' -d 'Regenerate MCP configs for all harnesses from the spec'
complete -c dot -n '__fish_use_subcommand' -f -a 'private-pkg-publish' -d 'Build and publish a private package'
complete -c dot -n '__fish_use_subcommand' -f -a 'skills' -d 'Maintain imported agent skills'
complete -c dot -n '__fish_use_subcommand' -f -a 'completions' -d 'Generate shell completions'
complete -c dot -n '__fish_use_subcommand' -f -a 'is-agent' -d 'Detect whether an AI coding agent is running dot'
complete -c dot -n '__fish_use_subcommand' -f -a 'agent-oxlint' -d 'Run the advisory generic Oxlint pass for cleanup work in an opted-in repository. Repository-owned Oxlint takes precedence. Pass changed paths normally, or use --all when explicitly requested.'
complete -c dot -n '__fish_use_subcommand' -f -a 'launch-floating-webapp' -d 'Launch one Omarchy webapp and place its new window in the target monitor\'s bottom-right corner, or reposition an existing window with --address. Width and height must be positive integers; margins must be non-negative.'
complete -c dot -n '__fish_use_subcommand' -f -a 'herdr-repo-open' -d 'Open or focus a repository workspace in the shared Herdr session. If the server is headless, open a tiled terminal and wait for a foreground client before focusing the workspace.'
complete -c dot -n '__fish_use_subcommand' -f -a 'workspace-setup' -d 'Launch or reuse desktop apps and rebuild the workspace layout'
complete -c dot -n '__fish_use_subcommand' -f -a 'workspace-relayout' -d 'Apply or capture a Hyprland workspace layout'
complete -c dot -n '__fish_use_subcommand' -f -a 'workspace-capture' -d 'Capture Hyprland workspace and window state'
complete -c dot -n '__fish_use_subcommand' -f -a 'workspace-restore' -d 'Restore a captured Hyprland workspace session'
complete -c dot -n '__fish_use_subcommand' -f -a 'usage' -d 'Report local-first usage analytics from NDJSON events under $XDG_STATE_HOME/tool-usage. Live events store canonical commands and recognised flag names, never positional values. Set DOT_USAGE_DISABLE=1 to disable live recording or DOT_USAGE_DIR to relocate storage.'
complete -c dot -n '__fish_use_subcommand' -f -a 'help' -d 'Show this help menu'
complete -c dot -n '__fish_use_subcommand; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_use_subcommand; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from init' -f
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt confirm no-confirm' -l confirm -d 'Compatibility flag; accepted but does not suppress prompts'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt confirm no-confirm' -l no-confirm -d 'Disable confirm'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt noninteractive no-noninteractive' -l noninteractive -d 'Skip the Hypr host questionnaire for this run'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt noninteractive no-noninteractive' -l no-noninteractive -d 'Disable noninteractive'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt interactive no-interactive' -l interactive -d 'Enable the Hypr host questionnaire when no host is selected'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt interactive no-interactive' -l no-interactive -d 'Disable interactive'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt force no-force' -l force -d 'Re-run init even if the machine looks initialised'
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt force no-force' -l no-force -d 'Disable force'
complete -c dot -n '__fish_seen_subcommand_from init; and begin; not __fish_contains_opt host; or contains -- (commandline -poc)[-1] --host; end' -l host -d 'Hypr host to link before stow' -r -f
complete -c dot -n '__fish_seen_subcommand_from init; and begin; not __fish_contains_opt log; or contains -- (commandline -poc)[-1] --log; end' -l log -d 'Init log path (default: ~/.local/state/dot/init.log)' -r -F
complete -c dot -n '__fish_seen_subcommand_from init; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt confirm no-confirm' -f -a '--confirm' -d 'Compatibility flag; accepted but does not suppress prompts'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt confirm no-confirm' -f -a '--no-confirm' -d 'Disable confirm'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt noninteractive no-noninteractive' -f -a '--noninteractive' -d 'Skip the Hypr host questionnaire for this run'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt noninteractive no-noninteractive' -f -a '--no-noninteractive' -d 'Disable noninteractive'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt interactive no-interactive' -f -a '--interactive' -d 'Enable the Hypr host questionnaire when no host is selected'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt interactive no-interactive' -f -a '--no-interactive' -d 'Disable interactive'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt force no-force' -f -a '--force' -d 'Re-run init even if the machine looks initialised'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt force no-force' -f -a '--no-force' -d 'Disable force'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt host' -f -a '--host' -d 'Hypr host to link before stow'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt log' -f -a '--log' -d 'Init log path (default: ~/.local/state/dot/init.log)'
complete -c dot -n '__fish_seen_subcommand_from init; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from install' -f
complete -c dot -n '__fish_seen_subcommand_from install; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from install; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from update' -f
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt pull no-pull' -l pull -d 'Run the repository pull phase only'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt pull no-pull' -l no-pull -d 'Disable pull'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt stow no-stow' -l stow -d 'Generate completions, sync MCP configs, and stow only'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt stow no-stow' -l no-stow -d 'Disable stow'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt app no-app' -l app -d 'Install Bun dependencies and rebuild the dot binary only'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt app no-app' -l no-app -d 'Disable app'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt check no-check' -l check -d 'Report core/system repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt check no-check' -l no-check -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt check-all no-check-all' -l check-all -d 'Report all tracked repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt check-all no-check-all' -l no-check-all -d 'Disable check-all'
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt no-self-update no-no-self-update' -l no-self-update -d 'Skip the internal self-update phase'
complete -c dot -n '__fish_seen_subcommand_from update; and begin; not __fish_contains_opt post-hook-repo; or contains -- (commandline -poc)[-1] --post-hook-repo; end' -l post-hook-repo -d 'Internal post-hook repository' -r -f
complete -c dot -n '__fish_seen_subcommand_from update; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pull no-pull' -f -a '--pull' -d 'Run the repository pull phase only'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pull no-pull' -f -a '--no-pull' -d 'Disable pull'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stow no-stow' -f -a '--stow' -d 'Generate completions, sync MCP configs, and stow only'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stow no-stow' -f -a '--no-stow' -d 'Disable stow'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt app no-app' -f -a '--app' -d 'Install Bun dependencies and rebuild the dot binary only'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt app no-app' -f -a '--no-app' -d 'Disable app'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--check' -d 'Report core/system repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--no-check' -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check-all no-check-all' -f -a '--check-all' -d 'Report all tracked repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check-all no-check-all' -f -a '--no-check-all' -d 'Disable check-all'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-self-update no-no-self-update' -f -a '--no-self-update' -d 'Skip the internal self-update phase'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt post-hook-repo' -f -a '--post-hook-repo' -d 'Internal post-hook repository'
complete -c dot -n '__fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from up' -f
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt pull no-pull' -l pull -d 'Run the repository pull phase only'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt pull no-pull' -l no-pull -d 'Disable pull'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt stow no-stow' -l stow -d 'Generate completions, sync MCP configs, and stow only'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt stow no-stow' -l no-stow -d 'Disable stow'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt app no-app' -l app -d 'Install Bun dependencies and rebuild the dot binary only'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt app no-app' -l no-app -d 'Disable app'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt check no-check' -l check -d 'Report core/system repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt check no-check' -l no-check -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt check-all no-check-all' -l check-all -d 'Report all tracked repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt check-all no-check-all' -l no-check-all -d 'Disable check-all'
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt no-self-update no-no-self-update' -l no-self-update -d 'Skip the internal self-update phase'
complete -c dot -n '__fish_seen_subcommand_from up; and begin; not __fish_contains_opt post-hook-repo; or contains -- (commandline -poc)[-1] --post-hook-repo; end' -l post-hook-repo -d 'Internal post-hook repository' -r -f
complete -c dot -n '__fish_seen_subcommand_from up; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pull no-pull' -f -a '--pull' -d 'Run the repository pull phase only'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pull no-pull' -f -a '--no-pull' -d 'Disable pull'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stow no-stow' -f -a '--stow' -d 'Generate completions, sync MCP configs, and stow only'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stow no-stow' -f -a '--no-stow' -d 'Disable stow'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt app no-app' -f -a '--app' -d 'Install Bun dependencies and rebuild the dot binary only'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt app no-app' -f -a '--no-app' -d 'Disable app'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--check' -d 'Report core/system repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--no-check' -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check-all no-check-all' -f -a '--check-all' -d 'Report all tracked repos behind upstream'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check-all no-check-all' -f -a '--no-check-all' -d 'Disable check-all'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-self-update no-no-self-update' -f -a '--no-self-update' -d 'Skip the internal self-update phase'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt post-hook-repo' -f -a '--post-hook-repo' -d 'Internal post-hook repository'
complete -c dot -n '__fish_seen_subcommand_from up; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from system-update' -f
complete -c dot -n '__fish_seen_subcommand_from system-update; and not __fish_contains_opt yes no-yes' -l yes -d 'Select every update without prompting'
complete -c dot -n '__fish_seen_subcommand_from system-update; and not __fish_contains_opt yes no-yes' -l no-yes -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from system-update; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from system-update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--yes' -d 'Select every update without prompting'
complete -c dot -n '__fish_seen_subcommand_from system-update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--no-yes' -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from system-update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from stow' -f
complete -c dot -n '__fish_seen_subcommand_from stow; and not __fish_contains_opt public no-public' -l public -d 'Stow public dotfiles only'
complete -c dot -n '__fish_seen_subcommand_from stow; and not __fish_contains_opt public no-public' -l no-public -d 'Disable public'
complete -c dot -n '__fish_seen_subcommand_from stow; and not __fish_contains_opt private no-private' -l private -d 'Stow private dotfiles only'
complete -c dot -n '__fish_seen_subcommand_from stow; and not __fish_contains_opt private no-private' -l no-private -d 'Disable private'
complete -c dot -n '__fish_seen_subcommand_from stow; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from stow; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt public no-public' -f -a '--public' -d 'Stow public dotfiles only'
complete -c dot -n '__fish_seen_subcommand_from stow; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt public no-public' -f -a '--no-public' -d 'Disable public'
complete -c dot -n '__fish_seen_subcommand_from stow; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt private no-private' -f -a '--private' -d 'Stow private dotfiles only'
complete -c dot -n '__fish_seen_subcommand_from stow; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt private no-private' -f -a '--no-private' -d 'Disable private'
complete -c dot -n '__fish_seen_subcommand_from stow; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove' -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove' -f -a 'add' -d 'Import a validated plugin checkout'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove' -f -a 'update' -d 'Update one or all managed plugins'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove' -f -a 'remove' -d 'Remove a managed plugin'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and not __fish_seen_subcommand_from add update remove; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and begin; not __fish_contains_opt section; or contains -- (commandline -poc)[-1] --section; end' -l section -r -f -a 'left center right'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and begin; not __fish_contains_opt before; or contains -- (commandline -poc)[-1] --before; end' -l before -d 'Place before this plugin' -r -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and begin; not __fish_contains_opt after; or contains -- (commandline -poc)[-1] --after; end' -l after -d 'Place after this plugin' -r -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt section' -f -a '--section'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt before' -f -a '--before' -d 'Place before this plugin'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt after' -f -a '--after' -d 'Place after this plugin'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from add' -r -F -d 'Validated live plugin checkout'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update' -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not __fish_contains_opt yes no-yes' -l yes -d 'Update without confirmation'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not __fish_contains_opt yes no-yes' -l no-yes -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--yes' -d 'Update without confirmation'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--no-yes' -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from update' -r -f -a '0 1' -d 'Compatibility confirmation value'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove' -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not __fish_contains_opt yes no-yes' -l yes -d 'Remove without confirmation'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not __fish_contains_opt yes no-yes' -l no-yes -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not __fish_contains_opt no-commit-offer no-no-commit-offer' -l no-commit-offer -d 'Do not offer the optional git-commit handoff'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--yes' -d 'Remove without confirmation'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt yes no-yes' -f -a '--no-yes' -d 'Disable yes'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-commit-offer no-no-commit-offer' -f -a '--no-commit-offer' -d 'Do not offer the optional git-commit handoff'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove' -r -f -a '0 1' -d 'Compatibility confirmation value'
complete -c dot -n '__fish_seen_subcommand_from omarchy-plugin; and __fish_seen_subcommand_from remove' -r -f -a '0 1' -d 'Compatibility commit-offer value'
complete -c dot -n '__fish_seen_subcommand_from omarchy-shell-config' -f
complete -c dot -n '__fish_seen_subcommand_from omarchy-shell-config; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from omarchy-shell-config; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from firewall' -f
complete -c dot -n '__fish_seen_subcommand_from firewall; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from firewall; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from doctor' -f
complete -c dot -n '__fish_seen_subcommand_from doctor; and not __fish_contains_opt open-opencode no-open-opencode' -l open-opencode -d 'Save the report and attempt to open it in OpenCode'
complete -c dot -n '__fish_seen_subcommand_from doctor; and not __fish_contains_opt open-opencode no-open-opencode' -l no-open-opencode -d 'Disable open-opencode'
complete -c dot -n '__fish_seen_subcommand_from doctor; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from doctor; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt open-opencode no-open-opencode' -f -a '--open-opencode' -d 'Save the report and attempt to open it in OpenCode'
complete -c dot -n '__fish_seen_subcommand_from doctor; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt open-opencode no-open-opencode' -f -a '--no-open-opencode' -d 'Disable open-opencode'
complete -c dot -n '__fish_seen_subcommand_from doctor; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from clean' -f
complete -c dot -n '__fish_seen_subcommand_from clean; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from clean; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from agents-sync' -f
complete -c dot -n '__fish_seen_subcommand_from agents-sync; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from agents-sync; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from notes-capture-sync' -f
complete -c dot -n '__fish_seen_subcommand_from notes-capture-sync; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from notes-capture-sync; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from setup-private-repo' -f
complete -c dot -n '__fish_seen_subcommand_from setup-private-repo; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from setup-private-repo; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from setup-public-repo' -f
complete -c dot -n '__fish_seen_subcommand_from setup-public-repo; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from setup-public-repo; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-diff' -f
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt no-fetch no-no-fetch' -l no-fetch -d 'Skip fetching from remotes'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt raw no-raw' -l raw -d 'Text summary output'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt raw no-raw' -l no-raw -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt bar-json no-bar-json' -l bar-json -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt bar-json no-bar-json' -l no-bar-json -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt panel-json no-panel-json' -l panel-json -d 'Full JSON snapshot for the native shell panel'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt panel-json no-panel-json' -l no-panel-json -d 'Disable panel-json'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt list-changed no-list-changed' -l list-changed -d 'Changed repos as rows'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt list-changed no-list-changed' -l no-list-changed -d 'Disable list-changed'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt list-all no-list-all' -l list-all -d 'All tracked repos as rows'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt list-all no-list-all' -l no-list-all -d 'Disable list-all'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-fetch no-no-fetch' -f -a '--no-fetch' -d 'Skip fetching from remotes'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--raw' -d 'Text summary output'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--no-raw' -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--bar-json' -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--no-bar-json' -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt panel-json no-panel-json' -f -a '--panel-json' -d 'Full JSON snapshot for the native shell panel'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt panel-json no-panel-json' -f -a '--no-panel-json' -d 'Disable panel-json'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-changed no-list-changed' -f -a '--list-changed' -d 'Changed repos as rows'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-changed no-list-changed' -f -a '--no-list-changed' -d 'Disable list-changed'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-all no-list-all' -f -a '--list-all' -d 'All tracked repos as rows'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-all no-list-all' -f -a '--no-list-all' -d 'Disable list-all'
complete -c dot -n '__fish_seen_subcommand_from git-diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from diff' -f
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt no-fetch no-no-fetch' -l no-fetch -d 'Skip fetching from remotes'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt raw no-raw' -l raw -d 'Text summary output'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt raw no-raw' -l no-raw -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt bar-json no-bar-json' -l bar-json -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt bar-json no-bar-json' -l no-bar-json -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt panel-json no-panel-json' -l panel-json -d 'Full JSON snapshot for the native shell panel'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt panel-json no-panel-json' -l no-panel-json -d 'Disable panel-json'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt list-changed no-list-changed' -l list-changed -d 'Changed repos as rows'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt list-changed no-list-changed' -l no-list-changed -d 'Disable list-changed'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt list-all no-list-all' -l list-all -d 'All tracked repos as rows'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt list-all no-list-all' -l no-list-all -d 'Disable list-all'
complete -c dot -n '__fish_seen_subcommand_from diff; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-fetch no-no-fetch' -f -a '--no-fetch' -d 'Skip fetching from remotes'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--raw' -d 'Text summary output'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--no-raw' -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--bar-json' -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--no-bar-json' -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt panel-json no-panel-json' -f -a '--panel-json' -d 'Full JSON snapshot for the native shell panel'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt panel-json no-panel-json' -f -a '--no-panel-json' -d 'Disable panel-json'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-changed no-list-changed' -f -a '--list-changed' -d 'Changed repos as rows'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-changed no-list-changed' -f -a '--no-list-changed' -d 'Disable list-changed'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-all no-list-all' -f -a '--list-all' -d 'All tracked repos as rows'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-all no-list-all' -f -a '--no-list-all' -d 'Disable list-all'
complete -c dot -n '__fish_seen_subcommand_from diff; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-commit' -f
complete -c dot -n '__fish_seen_subcommand_from git-commit; and begin; not __fish_contains_opt -s m message; or contains -- (commandline -poc)[-1] --message -m; end' -l message -s m -d 'Single-line commit subject' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-commit; and begin; not __fish_contains_opt path; or contains -- (commandline -poc)[-1] --path; end' -l path -d 'Commit only this file; repeatable' -r -F
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt amend no-amend' -l amend -d 'Amend the previous commit'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt amend no-amend' -l no-amend -d 'Disable amend'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt push no-push' -l push -d 'Push after committing'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt push no-push' -l no-push -d 'Disable push'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt dry-run no-dry-run' -l dry-run -d 'Preview without changing anything'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt dry-run no-dry-run' -l no-dry-run -d 'Disable dry-run'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s m message' -f -a '--message' -d 'Single-line commit subject'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt path' -f -a '--path' -d 'Commit only this file; repeatable'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt amend no-amend' -f -a '--amend' -d 'Amend the previous commit'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt amend no-amend' -f -a '--no-amend' -d 'Disable amend'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt push no-push' -f -a '--push' -d 'Push after committing'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt push no-push' -f -a '--no-push' -d 'Disable push'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run no-dry-run' -f -a '--dry-run' -d 'Preview without changing anything'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run no-dry-run' -f -a '--no-dry-run' -d 'Disable dry-run'
complete -c dot -n '__fish_seen_subcommand_from git-commit; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-notifications' -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt raw no-raw' -l raw -d 'Text summary of notification threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt raw no-raw' -l no-raw -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt bar-json no-bar-json' -l bar-json -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt bar-json no-bar-json' -l no-bar-json -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt list-threads no-list-threads' -l list-threads -d 'Notification threads as rows'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt list-threads no-list-threads' -l no-list-threads -d 'Disable list-threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt bar-filter no-bar-filter' -l bar-filter -d 'Apply watched-repo filtering'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt bar-filter no-bar-filter' -l no-bar-filter -d 'Disable bar-filter'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt all no-all' -l all -d 'Include read notifications'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt all no-all' -l no-all -d 'Disable all'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt participating no-participating' -l participating -d 'Only participating threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt participating no-participating' -l no-participating -d 'Disable participating'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and begin; not __fish_contains_opt since; or contains -- (commandline -poc)[-1] --since; end' -l since -d 'Only include notifications updated after this date' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and begin; not __fish_contains_opt mark-read; or contains -- (commandline -poc)[-1] --mark-read; end' -l mark-read -d 'Mark a thread as read' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and begin; not __fish_contains_opt mark-done; or contains -- (commandline -poc)[-1] --mark-done; end' -l mark-done -d 'Mark a thread as done' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and begin; not __fish_contains_opt ignore; or contains -- (commandline -poc)[-1] --ignore; end' -l ignore -d 'Ignore a thread' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and begin; not __fish_contains_opt unignore; or contains -- (commandline -poc)[-1] --unignore; end' -l unignore -d 'Stop ignoring a thread' -r -f
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt mark-bot-read no-mark-bot-read' -l mark-bot-read -d 'Mark bot notifications as read'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt mark-bot-read no-mark-bot-read' -l no-mark-bot-read -d 'Disable mark-bot-read'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt dry-run no-dry-run' -l dry-run -d 'Preview bot marking'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt dry-run no-dry-run' -l no-dry-run -d 'Disable dry-run'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--raw' -d 'Text summary of notification threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt raw no-raw' -f -a '--no-raw' -d 'Disable raw'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--bar-json' -d 'JSON output for status bars and shell modules'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-json no-bar-json' -f -a '--no-bar-json' -d 'Disable bar-json'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-threads no-list-threads' -f -a '--list-threads' -d 'Notification threads as rows'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt list-threads no-list-threads' -f -a '--no-list-threads' -d 'Disable list-threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-filter no-bar-filter' -f -a '--bar-filter' -d 'Apply watched-repo filtering'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bar-filter no-bar-filter' -f -a '--no-bar-filter' -d 'Disable bar-filter'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt all no-all' -f -a '--all' -d 'Include read notifications'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt all no-all' -f -a '--no-all' -d 'Disable all'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt participating no-participating' -f -a '--participating' -d 'Only participating threads'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt participating no-participating' -f -a '--no-participating' -d 'Disable participating'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt since' -f -a '--since' -d 'Only include notifications updated after this date'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt mark-read' -f -a '--mark-read' -d 'Mark a thread as read'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt mark-done' -f -a '--mark-done' -d 'Mark a thread as done'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt ignore' -f -a '--ignore' -d 'Ignore a thread'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt unignore' -f -a '--unignore' -d 'Stop ignoring a thread'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt mark-bot-read no-mark-bot-read' -f -a '--mark-bot-read' -d 'Mark bot notifications as read'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt mark-bot-read no-mark-bot-read' -f -a '--no-mark-bot-read' -d 'Disable mark-bot-read'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run no-dry-run' -f -a '--dry-run' -d 'Preview bot marking'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run no-dry-run' -f -a '--no-dry-run' -d 'Disable dry-run'
complete -c dot -n '__fish_seen_subcommand_from git-notifications; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from mcp-sync' -f
complete -c dot -n '__fish_seen_subcommand_from mcp-sync; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from mcp-sync; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish' -f
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt no-git no-no-git' -l no-git -d 'Skip package repo commit and push'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt skip-build no-skip-build' -l skip-build -d 'Publish an existing artifact'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt skip-build no-skip-build' -l no-skip-build -d 'Disable skip-build'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt install no-install' -l install -d 'Install after publishing'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt install no-install' -l no-install -d 'Disable install'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-git no-no-git' -f -a '--no-git' -d 'Skip package repo commit and push'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skip-build no-skip-build' -f -a '--skip-build' -d 'Publish an existing artifact'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skip-build no-skip-build' -f -a '--no-skip-build' -d 'Disable skip-build'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt install no-install' -f -a '--install' -d 'Install after publishing'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt install no-install' -f -a '--no-install' -d 'Disable install'
complete -c dot -n '__fish_seen_subcommand_from private-pkg-publish; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f -a 'validate' -d 'Validate the standalone skills repository'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f -a 'import' -d 'Import or refresh a reviewed skill snapshot'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f -a 'updates' -d 'Check/apply imported skill updates'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f -a 'check' -d 'Check adapted imports against upstream'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent' -f -a 'updates-agent' -d 'Run skill update automation'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from validate import updates check updates-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from validate' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from validate; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from validate; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not __fish_contains_opt apply no-apply' -l apply -d 'Apply a clean imported snapshot'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not __fish_contains_opt apply no-apply' -l no-apply -d 'Disable apply'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not __fish_contains_opt metadata-only no-metadata-only' -l metadata-only -d 'Materialise metadata only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not __fish_contains_opt metadata-only no-metadata-only' -l no-metadata-only -d 'Disable metadata-only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and begin; not __fish_contains_opt reviewed-sha; or contains -- (commandline -poc)[-1] --reviewed-sha; end' -l reviewed-sha -d 'Set the reviewed upstream SHA' -r -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt apply no-apply' -f -a '--apply' -d 'Apply a clean imported snapshot'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt apply no-apply' -f -a '--no-apply' -d 'Disable apply'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt metadata-only no-metadata-only' -f -a '--metadata-only' -d 'Materialise metadata only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt metadata-only no-metadata-only' -f -a '--no-metadata-only' -d 'Disable metadata-only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt reviewed-sha' -f -a '--reviewed-sha' -d 'Set the reviewed upstream SHA'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from import; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt check no-check' -l check -d 'Check only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt check no-check' -l no-check -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt update no-update' -l update -d 'Apply clean updates'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt update no-update' -l no-update -d 'Disable update'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt json no-json' -l json -d 'Report as JSON'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt json no-json' -l no-json -d 'Disable json'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and begin; not __fish_contains_opt skill; or contains -- (commandline -poc)[-1] --skill; end' -l skill -d 'Limit to one skill' -r -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt no-commit no-no-commit' -l no-commit -d 'Apply without committing'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt skip-review no-skip-review' -l skip-review -d 'Skip local-edit review'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt skip-review no-skip-review' -l no-skip-review -d 'Disable skip-review'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--check' -d 'Check only'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt check no-check' -f -a '--no-check' -d 'Disable check'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt update no-update' -f -a '--update' -d 'Apply clean updates'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt update no-update' -f -a '--no-update' -d 'Disable update'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt json no-json' -f -a '--json' -d 'Report as JSON'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt json no-json' -f -a '--no-json' -d 'Disable json'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skill' -f -a '--skill' -d 'Limit to one skill'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-commit no-no-commit' -f -a '--no-commit' -d 'Apply without committing'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skip-review no-skip-review' -f -a '--skip-review' -d 'Skip local-edit review'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skip-review no-skip-review' -f -a '--no-skip-review' -d 'Disable skip-review'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not __fish_contains_opt open-opencode no-open-opencode' -l open-opencode -d 'Attempt OpenCode analysis'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not __fish_contains_opt open-opencode no-open-opencode' -l no-open-opencode -d 'Disable open-opencode'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not __fish_contains_opt diff-origin no-diff-origin' -l diff-origin -d 'Diff against upstream origins'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not __fish_contains_opt diff-origin no-diff-origin' -l no-diff-origin -d 'Disable diff-origin'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and begin; not __fish_contains_opt skill; or contains -- (commandline -poc)[-1] --skill; end' -l skill -d 'Check one skill' -r -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt open-opencode no-open-opencode' -f -a '--open-opencode' -d 'Attempt OpenCode analysis'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt open-opencode no-open-opencode' -f -a '--no-open-opencode' -d 'Disable open-opencode'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt diff-origin no-diff-origin' -f -a '--diff-origin' -d 'Diff against upstream origins'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt diff-origin no-diff-origin' -f -a '--no-diff-origin' -d 'Disable diff-origin'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skill' -f -a '--skill' -d 'Check one skill'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from check; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and not __fish_seen_subcommand_from github device' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and not __fish_seen_subcommand_from github device' -f -a 'github' -d 'Run GitHub skill update automation'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and not __fish_seen_subcommand_from github device' -f -a 'device' -d 'Run local device skill update automation'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and not __fish_seen_subcommand_from github device; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and not __fish_seen_subcommand_from github device; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from github' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from github; and begin; not __fish_contains_opt skills-dir; or contains -- (commandline -poc)[-1] --skills-dir; end' -l skills-dir -d 'Use this Skills checkout' -r -F
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from github; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from github; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt skills-dir' -f -a '--skills-dir' -d 'Use this Skills checkout'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from github; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device' -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and begin; not __fish_contains_opt config; or contains -- (commandline -poc)[-1] --config; end' -l config -d 'Use this YAML config' -r -F
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and begin; not __fish_contains_opt run-id; or contains -- (commandline -poc)[-1] --run-id; end' -l run-id -d 'Wait for this workflow run' -r -f
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt config' -f -a '--config' -d 'Use this YAML config'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt run-id' -f -a '--run-id' -d 'Wait for this workflow run'
complete -c dot -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from updates-agent; and __fish_seen_subcommand_from device; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from completions' -f
complete -c dot -n '__fish_seen_subcommand_from completions; and not __fish_contains_opt stdout no-stdout' -l stdout -d 'Print instead of writing'
complete -c dot -n '__fish_seen_subcommand_from completions; and not __fish_contains_opt stdout no-stdout' -l no-stdout -d 'Disable stdout'
complete -c dot -n '__fish_seen_subcommand_from completions; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from completions; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stdout no-stdout' -f -a '--stdout' -d 'Print instead of writing'
complete -c dot -n '__fish_seen_subcommand_from completions; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt stdout no-stdout' -f -a '--no-stdout' -d 'Disable stdout'
complete -c dot -n '__fish_seen_subcommand_from completions; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from completions' -r -f -a 'bash fish zsh' -d 'Shell to generate completions for'
complete -c dot -n '__fish_seen_subcommand_from is-agent' -f
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not __fish_contains_opt -s q quiet no-quiet' -l quiet -s q
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not __fish_contains_opt -s q quiet no-quiet' -l no-quiet
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not __fish_contains_opt json no-json' -l json -d 'Print JSON'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not __fish_contains_opt json no-json' -l no-json -d 'Disable json'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s q quiet no-quiet' -f -a '--quiet'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s q quiet no-quiet' -f -a '--no-quiet'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt json no-json' -f -a '--json' -d 'Print JSON'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt json no-json' -f -a '--no-json' -d 'Disable json'
complete -c dot -n '__fish_seen_subcommand_from is-agent; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not __fish_contains_opt all no-all' -l all -d 'Lint the complete repository tree'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not __fish_contains_opt all no-all' -l no-all -d 'Disable all'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt all no-all' -f -a '--all' -d 'Lint the complete repository tree'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt all no-all' -f -a '--no-all' -d 'Disable all'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from agent-oxlint' -r -F
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp' -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt monitor; or contains -- (commandline -poc)[-1] --monitor; end' -l monitor -d 'Target monitor' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt workspace; or contains -- (commandline -poc)[-1] --workspace; end' -l workspace -d 'Target workspace' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt width; or contains -- (commandline -poc)[-1] --width; end' -l width -d 'Window width' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt height; or contains -- (commandline -poc)[-1] --height; end' -l height -d 'Window height' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt right-margin; or contains -- (commandline -poc)[-1] --right-margin; end' -l right-margin -d 'Right margin' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt bottom-margin; or contains -- (commandline -poc)[-1] --bottom-margin; end' -l bottom-margin -d 'Bottom margin' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and begin; not __fish_contains_opt address; or contains -- (commandline -poc)[-1] --address; end' -l address -d 'Existing window address' -r -f
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt monitor' -f -a '--monitor' -d 'Target monitor'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt workspace' -f -a '--workspace' -d 'Target workspace'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt width' -f -a '--width' -d 'Window width'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt height' -f -a '--height' -d 'Window height'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt right-margin' -f -a '--right-margin' -d 'Right margin'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt bottom-margin' -f -a '--bottom-margin' -d 'Bottom margin'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt address' -f -a '--address' -d 'Existing window address'
complete -c dot -n '__fish_seen_subcommand_from launch-floating-webapp; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not __fish_contains_opt pane no-pane' -l pane -d 'Run in a new pane'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not __fish_contains_opt pane no-pane' -l no-pane -d 'Disable pane'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pane no-pane' -f -a '--pane' -d 'Run in a new pane'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt pane no-pane' -f -a '--no-pane' -d 'Disable pane'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from herdr-repo-open' -r -F -d 'Repository working directory'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup' -f
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not __fish_contains_opt step-through step no-step-through' -l step-through -l step -d 'Pause after each logged step'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not __fish_contains_opt step-through step no-step-through' -l no-step-through -d 'Disable step-through'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and begin; not __fish_contains_opt speed-multiplier; or contains -- (commandline -poc)[-1] --speed-multiplier; end' -l speed-multiplier -d 'Multiply built-in sleep durations' -r -f
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and begin; not __fish_contains_opt sleep; or contains -- (commandline -poc)[-1] --sleep; end' -l sleep -d 'Wait before running setup logic' -r -f
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not __fish_contains_opt fast no-fast' -l fast -d 'Use a speed multiplier of 1'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not __fish_contains_opt fast no-fast' -l no-fast -d 'Disable fast'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and begin; not __fish_contains_opt temp-workspace; or contains -- (commandline -poc)[-1] --temp-workspace; end' -l temp-workspace -d 'Numeric temporary workspace' -r -f
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and begin; not __fish_contains_opt move-dispatcher; or contains -- (commandline -poc)[-1] --move-dispatcher; end' -l move-dispatcher -d 'Window move dispatcher' -r -f -a 'movetoworkspace movetoworkspacesilent'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and begin; not __fish_contains_opt log-file; or contains -- (commandline -poc)[-1] --log-file; end' -l log-file -d 'Write the run log to this file' -r -F
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt step-through step no-step-through' -f -a '--step-through' -d 'Pause after each logged step'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt step-through step no-step-through' -f -a '--no-step-through' -d 'Disable step-through'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt speed-multiplier' -f -a '--speed-multiplier' -d 'Multiply built-in sleep durations'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt sleep' -f -a '--sleep' -d 'Wait before running setup logic'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt fast no-fast' -f -a '--fast' -d 'Use a speed multiplier of 1'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt fast no-fast' -f -a '--no-fast' -d 'Disable fast'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt temp-workspace' -f -a '--temp-workspace' -d 'Numeric temporary workspace'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt move-dispatcher' -f -a '--move-dispatcher' -d 'Window move dispatcher'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt log-file' -f -a '--log-file' -d 'Write the run log to this file'
complete -c dot -n '__fish_seen_subcommand_from workspace-setup; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout' -f
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not __fish_contains_opt edit no-edit' -l edit -d 'Capture or overwrite a preset'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not __fish_contains_opt edit no-edit' -l no-edit -d 'Disable edit'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt edit no-edit' -f -a '--edit' -d 'Capture or overwrite a preset'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt edit no-edit' -f -a '--no-edit' -d 'Disable edit'
complete -c dot -n '__fish_seen_subcommand_from workspace-relayout; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture' -f
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not __fish_contains_opt current-workspace current no-current-workspace' -l current-workspace -l current
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not __fish_contains_opt current-workspace current no-current-workspace' -l no-current-workspace
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and begin; not __fish_contains_opt output; or contains -- (commandline -poc)[-1] --output; end' -l output -d 'Write to this file' -r -F
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and begin; not __fish_contains_opt state-dir; or contains -- (commandline -poc)[-1] --state-dir; end' -l state-dir -d 'Capture state directory' -r -F
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt current-workspace current no-current-workspace' -f -a '--current-workspace'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt current-workspace current no-current-workspace' -f -a '--no-current-workspace'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt output' -f -a '--output' -d 'Write to this file'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt state-dir' -f -a '--state-dir' -d 'Capture state directory'
complete -c dot -n '__fish_seen_subcommand_from workspace-capture; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore' -f
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not __fish_contains_opt dry-run dryrun no-dry-run' -l dry-run -l dryrun
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not __fish_contains_opt dry-run dryrun no-dry-run' -l no-dry-run
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and begin; not __fish_contains_opt file; or contains -- (commandline -poc)[-1] --file; end' -l file -d 'Restore this capture' -r -F
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and begin; not __fish_contains_opt state-dir; or contains -- (commandline -poc)[-1] --state-dir; end' -l state-dir -d 'Capture state directory' -r -F
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not __fish_contains_opt no-launch no-no-launch' -l no-launch -d 'Do not launch missing apps'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not __fish_contains_opt no-move no-no-move' -l no-move -d 'Do not move matched windows'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run dryrun no-dry-run' -f -a '--dry-run'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt dry-run dryrun no-dry-run' -f -a '--no-dry-run'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt file' -f -a '--file' -d 'Restore this capture'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt state-dir' -f -a '--state-dir' -d 'Capture state directory'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-launch no-no-launch' -f -a '--no-launch' -d 'Do not launch missing apps'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt no-move no-no-move' -f -a '--no-move' -d 'Do not move matched windows'
complete -c dot -n '__fish_seen_subcommand_from workspace-restore; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from usage' -f
complete -c dot -n '__fish_seen_subcommand_from usage; and begin; not __fish_contains_opt days; or contains -- (commandline -poc)[-1] --days; end' -l days -d 'Window in days' -r -f
complete -c dot -n '__fish_seen_subcommand_from usage; and begin; not __fish_contains_opt format; or contains -- (commandline -poc)[-1] --format; end' -l format -r -f -a 'text json agent-context'
complete -c dot -n '__fish_seen_subcommand_from usage; and begin; not __fish_contains_opt root; or contains -- (commandline -poc)[-1] --root; end' -l root -r -F
complete -c dot -n '__fish_seen_subcommand_from usage; and not __fish_contains_opt history no-history' -l history -d 'Backfill from shell history'
complete -c dot -n '__fish_seen_subcommand_from usage; and not __fish_contains_opt history no-history' -l no-history -d 'Disable history'
complete -c dot -n '__fish_seen_subcommand_from usage; and not __fish_contains_opt apply no-apply' -l apply -d 'Write backfilled events'
complete -c dot -n '__fish_seen_subcommand_from usage; and not __fish_contains_opt apply no-apply' -l no-apply -d 'Disable apply'
complete -c dot -n '__fish_seen_subcommand_from usage; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt days' -f -a '--days' -d 'Window in days'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt format' -f -a '--format'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt root' -f -a '--root'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt history no-history' -f -a '--history' -d 'Backfill from shell history'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt history no-history' -f -a '--no-history' -d 'Disable history'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt apply no-apply' -f -a '--apply' -d 'Write backfilled events'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt apply no-apply' -f -a '--no-apply' -d 'Disable apply'
complete -c dot -n '__fish_seen_subcommand_from usage; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from usage' -r -f -a 'summary stale path backfill' -d 'Analytics operation'
complete -c dot -n '__fish_seen_subcommand_from help' -f
complete -c dot -n '__fish_seen_subcommand_from help; and not __fish_contains_opt -s h help no-help' -l help -s h -d 'Show help information'
complete -c dot -n '__fish_seen_subcommand_from help; and not string match -q -- "-*" (commandline -ct); and not __fish_contains_opt -s h help no-help' -f -a '--help' -d 'Show help information'

###-end-dot-completions-###