// Generates the OpenCode reference pages under
// docs/src/content/docs/agents/opencode/ from the live OpenCode assets in this repo:
//   agents/.config/opencode/{agents,commands,plugins}
// Skills are catalogued in timmo001/skills SKILLS.md, not generated here.
// Run with: mise run docs:gen:opencode
//
// Do not edit the generated pages by hand. Change the source assets and re-run
// this script (the opencode-publish workflow also regenerates them).
import { readFile, readdir, writeFile, mkdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(root, '..');
const outDir = path.join(root, 'src/content/docs/agents/opencode');

const BRANCH = 'distro/arch-omarchy';
const BLOB = `https://github.com/timmo001/dotfiles/blob/${BRANCH}`;

const OPENCODE_PREFIX = 'agents/.config/opencode';

/** Read the YAML frontmatter block of a markdown file as a key/value map. */
async function frontmatter(file: string): Promise<Record<string, string>> {
  const text = await readFile(file, 'utf8');
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  const fields: Record<string, string> = {};
  if (!match) return fields;
  const rows = match[1].split('\n');
  for (let i = 0; i < rows.length; i++) {
    const m = rows[i].match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    if (!m) continue;
    let value = m[2].trim();
    if (/^[>|][+-]?$/.test(value)) {
      // YAML block scalar: collect the following indented/blank lines.
      const collected: string[] = [];
      while (i + 1 < rows.length && (rows[i + 1].trim() === '' || /^\s/.test(rows[i + 1]))) {
        collected.push(rows[++i].trim());
      }
      value = collected.join(' ').replace(/\s+/g, ' ').trim();
    } else if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    fields[m[1]] = value;
  }
  return fields;
}

/** Extract the JSDoc `@file` description from a plugin source file. */
async function pluginDescription(file: string): Promise<string> {
  const text = await readFile(file, 'utf8');
  const match = text.match(/@file\s+(.*)/);
  return match ? match[1].replace(/\.?\s*$/, '').trim() : '';
}

const escapeCell = (value: string) => value.replace(/[\\|]/g, '\\$&');

/** Recursively list markdown files under a directory, relative to it. */
async function listMarkdown(dir: string, base = dir): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir)) {
    const full = path.join(dir, entry);
    if ((await stat(full)).isDirectory()) {
      out.push(...(await listMarkdown(full, base)));
    } else if (entry.endsWith('.md')) {
      out.push(path.relative(base, full));
    }
  }
  return out.sort();
}

function pageHeader(
  title: string,
  description: string,
  order: number,
  sidebarLabel?: string,
): string[] {
  const lines = [
    '---',
    `title: ${title}`,
    `description: ${description}`,
    'sidebar:',
  ];
  if (sidebarLabel) {
    lines.push(`  label: ${sidebarLabel}`);
  }
  lines.push(
    `  order: ${order}`,
    '---',
    '',
    '<!-- Generated by `mise run docs:gen:opencode` from the OpenCode assets in this repo. Do not edit by hand. -->',
    '',
  );
  return lines;
}

async function generateAgents(): Promise<void> {
  const dir = path.join(repoRoot, OPENCODE_PREFIX, 'agents');
  const files = (await readdir(dir)).filter((f) => f.endsWith('.md')).sort();
  const lines = pageHeader(
    'Agents',
    'OpenCode agents defined in this repo.',
    2,
  );
  lines.push(
    'Agents set the execution posture (permissions, tool access, delegation) for OpenCode sessions. They are published to [`opencode-config`](https://github.com/timmo001/opencode-config) and loaded from `~/.config/opencode/agents/`.',
    '',
    '| Agent | Description |',
    '| --- | --- |',
  );
  for (const file of files) {
    const name = file.replace(/\.md$/, '');
    const fm = await frontmatter(path.join(dir, file));
    if (fm.hidden === 'true') continue;
    const link = `${BLOB}/${OPENCODE_PREFIX}/agents/${file}`;
    lines.push(`| [\`${name}\`](${link}) | ${escapeCell(fm.description ?? '')} |`);
  }
  lines.push('');
  await writeFile(path.join(outDir, 'agents.md'), `${lines.join('\n')}`);
}

async function generateCommands(): Promise<void> {
  const dir = path.join(repoRoot, OPENCODE_PREFIX, 'commands');
  const files = await listMarkdown(dir);
  const lines = pageHeader(
    'Commands',
    'OpenCode slash commands defined in this repo.',
    3,
  );
  lines.push(
    'Commands are thin routing prompts: they name an agent, declare required skills or injected context, and define the output shape. They are loaded from `~/.config/opencode/commands/`.',
    '',
    '| Command | Description | Agent |',
    '| --- | --- | --- |',
  );
  for (const rel of files) {
    const name = rel.replace(/\.md$/, '');
    const fm = await frontmatter(path.join(dir, rel));
    const link = `${BLOB}/${OPENCODE_PREFIX}/commands/${rel}`;
    lines.push(
      `| [\`/${name}\`](${link}) | ${escapeCell(fm.description ?? '')} | \`${fm.agent ?? 'default'}\` |`,
    );
  }
  lines.push('');
  await writeFile(path.join(outDir, 'commands.md'), `${lines.join('\n')}`);
}

async function generatePlugins(): Promise<void> {
  const directories = ['plugins'];
  const files = (
    await Promise.all(
      directories.map(async (directory) =>
        (await readdir(path.join(repoRoot, OPENCODE_PREFIX, directory)))
          .filter((file) => file.endsWith('.ts'))
          .map((file) => ({ directory, file })),
      ),
    )
  ).flat();
  files.sort((a, b) => a.file.localeCompare(b.file));
  const lines = pageHeader(
    'Plugins',
    'OpenCode lifecycle plugins defined in this repo.',
    5,
  );
  lines.push(
    'Plugins provide context, evidence, or enforcement hooks for OpenCode. Server plugins are loaded from `~/.config/opencode/plugins/`.',
    '',
    '| Plugin | Description |',
    '| --- | --- |',
  );
  for (const { directory, file } of files) {
    const name = file.replace(/\.ts$/, '');
    const desc = await pluginDescription(path.join(repoRoot, OPENCODE_PREFIX, directory, file));
    const link = `${BLOB}/${OPENCODE_PREFIX}/${directory}/${file}`;
    lines.push(`| [\`${name}\`](${link}) | ${escapeCell(desc)} |`);
  }
  lines.push('');
  await writeFile(path.join(outDir, 'plugins.md'), `${lines.join('\n')}`);
}

await mkdir(outDir, { recursive: true });
await Promise.all([
  generateAgents(),
  generateCommands(),
  generatePlugins(),
]);
console.log('Wrote agents/opencode/{agents,commands,plugins}.md');
