import { Effect, FileSystem, Schema } from "effect";
import { dirname, join, resolve } from "node:path";
import { writeFileAtomic } from "../../lib/atomicWrite.js";
import { CommandExecutor } from "../../services/CommandExecutor.js";
import { Config } from "../../services/Config.js";
import { OutputLog } from "../../services/OutputLog.js";
import { displayPath } from "../../lib/paths.js";
import { cliStyler } from "../../lib/ansi.js";
import { buildRepoMcpEntries } from "./adapters.js";
import { formatJson } from "./formatJson.js";

const CONFIG_PATH = ".opencode/opencode.jsonc";

const HEADER =
  "// Generated by dot mcp sync from private dot-git.yml. Do not edit.\n";

// Files written before the command was renamed from mcp-sync are still owned.
const OWNED_HEADERS = [
  HEADER,
  "// Generated by dot mcp-sync from private dot-git.yml. Do not edit.\n",
];

/** Failure to apply a repository's private OpenCode MCP configuration. */
export class RepoMcpError extends Schema.TaggedError<RepoMcpError>()(
  "RepoMcpError",
  {
    message: Schema.String,
  },
) {}

const rememberRepositories = Effect.fn("McpSync.rememberRepositories")(
  (file: string, directories: readonly string[]) =>
    Effect.try({
      try: () =>
        writeFileAtomic(file, JSON.stringify(directories), {
          mode: 0o600,
          createDirectory: true,
        }),
      catch: (error) => new RepoMcpError({ message: String(error) }),
    }),
);

/** Reconcile generated, Git-ignored repository MCP configs with private opt-ins. */
export const syncRepoMcpConfigs = Effect.gen(function* () {
  const { gitConfig, mcpConfig, stateDir } = yield* Config;
  const executor = yield* CommandExecutor;
  const log = yield* OutputLog;
  const fs = yield* FileSystem.FileSystem;

  const repoMcpError = (error: { readonly message: string }) =>
    new RepoMcpError({ message: error.message });

  if (!gitConfig.present) return;

  if (!gitConfig.valid)
    return yield* new RepoMcpError({
      message: gitConfig.diagnostics.join("; "),
    });

  const manifest = join(stateDir, "mcp-repositories.json");

  const selected = gitConfig.repositories.filter(
    (repo) => repo.opencodeMcp?.length,
  );

  const configs = yield* Effect.try({
    try: () =>
      new Map(
        selected.map((repo) => [
          repo.path,
          HEADER +
            formatJson({
              $schema: "https://opencode.ai/config.json",
              mcp: {
                servers: buildRepoMcpEntries(
                  mcpConfig.spec,
                  repo.opencodeMcp ?? [],
                ),
              },
            }),
        ]),
      ),
    catch: (error) => new RepoMcpError({ message: String(error) }),
  });

  const previous = yield* Effect.gen(function* () {
    if (!(yield* fs.exists(manifest))) return [];

    const text = yield* fs.readFileString(manifest);

    return yield* Effect.try(() => JSON.parse(text));
  }).pipe(
    Effect.flatMap(Schema.decodeUnknownEffect(Schema.Array(Schema.String))),
    Effect.mapError(repoMcpError),
  );

  const directories = [...new Set([...previous, ...configs.keys()])];

  // Retain ownership if a later repository fails partway through the sync.
  yield* rememberRepositories(manifest, directories);

  for (const directory of directories) {
    if (!(yield* fs.exists(directory).pipe(Effect.mapError(repoMcpError)))) {
      yield* log.warn(
        `Skipped missing MCP repository: ${displayPath(directory)}`,
      );
      continue;
    }

    const target = join(directory, CONFIG_PATH);
    const content = configs.get(directory);

    const existing = yield* Effect.gen(function* () {
      if (!(yield* fs.exists(target))) return undefined;

      return yield* fs.readFileString(target);
    }).pipe(Effect.mapError(repoMcpError));

    if (
      existing !== undefined &&
      !OWNED_HEADERS.some((header) => existing.startsWith(header))
    )
      return yield* new RepoMcpError({
        message: `Not a dot-managed file: ${displayPath(target)}`,
      });

    const tracked = yield* executor.run(
      "git",
      ["ls-files", "--", CONFIG_PATH],
      { cwd: directory },
    );

    if (tracked.trim())
      return yield* new RepoMcpError({
        message: `Cannot manage tracked config: ${displayPath(target)}`,
      });

    const exclude = resolve(
      directory,
      (yield* executor.run("git", ["rev-parse", "--git-path", "info/exclude"], {
        cwd: directory,
      })).trim(),
    );

    yield* Effect.gen(function* () {
      if (content === undefined) {
        if (existing !== undefined) yield* fs.remove(target);

        return;
      }

      const ignored = (yield* fs.exists(exclude))
        ? yield* fs.readFileString(exclude)
        : "";

      if (!ignored.split(/\r?\n/).includes(`/${CONFIG_PATH}`)) {
        yield* fs.makeDirectory(dirname(exclude), { recursive: true });
        yield* fs.writeFileString(
          exclude,
          `${ignored}${ignored.endsWith("\n") || !ignored ? "" : "\n"}/${CONFIG_PATH}\n`,
        );
      }

      if (existing === content) return;

      yield* Effect.try(() =>
        writeFileAtomic(target, content, {
          mode: 0o600,
          createDirectory: true,
        }),
      );
    }).pipe(Effect.mapError(repoMcpError));
    const style = cliStyler();

    yield* log.info(
      content === undefined
        ? `${style.warn("Removed")} OpenCode MCP ${style.dim(displayPath(directory))}`
        : style.dim(`OpenCode MCP synced: ${displayPath(directory)}`),
    );
  }

  yield* rememberRepositories(manifest, [...configs.keys()]);
});
