import { Effect, Schema } from "effect";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { CommandExecutor } from "../../services/CommandExecutor.js";
import { Config } from "../../services/Config.js";
import { OutputLog } from "../../services/OutputLog.js";
import { displayPath } from "../../lib/paths.js";
import { buildRepoMcpEntries } from "./adapters.js";
import { formatJson } from "./formatJson.js";

const CONFIG_PATH = ".opencode/opencode.jsonc";

const HEADER =
  "// Generated by dot mcp-sync from private dot-git.yml. Do not edit.\n";

/** Failure to apply a repository's private OpenCode MCP configuration. */
export class RepoMcpError extends Schema.TaggedError<RepoMcpError>()(
  "RepoMcpError",
  {
    message: Schema.String,
  },
) {}

const rememberRepositories = Effect.fn("McpSync.rememberRepositories")(
  (file: string, directories: readonly string[]) =>
    Effect.try({
      try: () => {
        mkdirSync(dirname(file), { recursive: true });
        const temporary = `${file}.tmp.${process.pid}`;
        writeFileSync(temporary, JSON.stringify(directories), { mode: 0o600 });
        renameSync(temporary, file);
      },
      catch: (error) => new RepoMcpError({ message: String(error) }),
    }),
);

/** Reconcile generated, Git-ignored repository MCP configs with private opt-ins. */
export const syncRepoMcpConfigs = Effect.gen(function* () {
  const { gitConfig, mcpConfig, stateDir } = yield* Config;
  const executor = yield* CommandExecutor;
  const log = yield* OutputLog;

  if (!gitConfig.present) return;

  if (!gitConfig.valid)
    return yield* new RepoMcpError({
      message: gitConfig.diagnostics.join("; "),
    });

  const manifest = join(stateDir, "mcp-repositories.json");

  const selected = gitConfig.repositories.filter(
    (repo) => repo.opencodeMcp?.length,
  );

  const configs = yield* Effect.try({
    try: () =>
      new Map(
        selected.map((repo) => [
          repo.path,
          HEADER +
            formatJson({
              $schema: "https://opencode.ai/config.json",
              mcp: {
                servers: buildRepoMcpEntries(
                  mcpConfig.spec,
                  repo.opencodeMcp ?? [],
                ),
              },
            }),
        ]),
      ),
    catch: (error) => new RepoMcpError({ message: String(error) }),
  });

  const previous = yield* Effect.try({
    try: () =>
      existsSync(manifest) ? JSON.parse(readFileSync(manifest, "utf8")) : [],
    catch: (error) => new RepoMcpError({ message: String(error) }),
  }).pipe(
    Effect.flatMap(Schema.decodeUnknownEffect(Schema.Array(Schema.String))),
    Effect.mapError((error) => new RepoMcpError({ message: String(error) })),
  );

  const directories = [...new Set([...previous, ...configs.keys()])];

  // Retain ownership if a later repository fails partway through the sync.
  yield* rememberRepositories(manifest, directories);

  for (const directory of directories) {
    if (!existsSync(directory)) {
      yield* log.warn(
        `Skipped missing MCP repository: ${displayPath(directory)}`,
      );
      continue;
    }

    const target = join(directory, CONFIG_PATH);
    const content = configs.get(directory);

    const existing = yield* Effect.try({
      try: () =>
        existsSync(target) ? readFileSync(target, "utf8") : undefined,
      catch: (error) => new RepoMcpError({ message: String(error) }),
    });

    if (existing !== undefined && !existing.startsWith(HEADER))
      return yield* new RepoMcpError({
        message: `Not a dot-managed file: ${displayPath(target)}`,
      });

    const tracked = yield* executor.run(
      "git",
      ["ls-files", "--", CONFIG_PATH],
      { cwd: directory },
    );

    if (tracked.trim())
      return yield* new RepoMcpError({
        message: `Cannot manage tracked config: ${displayPath(target)}`,
      });

    const exclude = resolve(
      directory,
      (yield* executor.run("git", ["rev-parse", "--git-path", "info/exclude"], {
        cwd: directory,
      })).trim(),
    );

    yield* Effect.try({
      try: () => {
        if (content === undefined) {
          if (existing !== undefined) unlinkSync(target);

          return;
        }

        const ignored = existsSync(exclude)
          ? readFileSync(exclude, "utf8")
          : "";

        if (!ignored.split(/\r?\n/).includes(`/${CONFIG_PATH}`)) {
          mkdirSync(dirname(exclude), { recursive: true });
          writeFileSync(
            exclude,
            `${ignored}${ignored.endsWith("\n") || !ignored ? "" : "\n"}/${CONFIG_PATH}\n`,
          );
        }

        if (existing === content) return;
        mkdirSync(dirname(target), { recursive: true });
        const temporary = `${target}.tmp.${process.pid}`;
        writeFileSync(temporary, content, { mode: 0o600 });
        renameSync(temporary, target);
      },
      catch: (error) => new RepoMcpError({ message: String(error) }),
    });
    yield* log.info(
      `OpenCode MCP ${content === undefined ? "removed" : "synced"}: ${displayPath(directory)}`,
    );
  }

  yield* rememberRepositories(manifest, [...configs.keys()]);
});
