---
name: Lint

on:
  push:
    branches:
      - distro/arch-omarchy
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master
    with:
      scandir: ./scripts/.local/bin
      severity: warning
      ignore_names: gh-import-dotenv-to-secrets
